name: Test PowerShell on Windows
on: push

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          ./ramlog.ps1
